services:
  # ── BACKEND SERVICES ────────────────────────────────────────────────────────
  - type: web
    name: qma-auth-service
    runtime: docker
    dockerContext: .
    dockerfilePath: AuthService/Dockerfile
    region: ohio
    plan: free
    healthCheckPath: /health
    envVars:
      - key: ConnectionStrings__DefaultConnection
        fromDatabase:
          name: qma-db
          property: connectionString
      - key: Jwt__SecretKey
        value: btOUxwrOAwpVRLmc*#RfL8sdI#vYAZlgRuvO%qpRzxFHKq1V!
      - key: Jwt__Issuer
        value: QuantityMeasurementAPI
      - key: Jwt__Audience
        value: QuantityMeasurementClient

  - type: web
    name: qma-quantity-service
    runtime: docker
    dockerContext: .
    dockerfilePath: QuantityService/Dockerfile
    region: ohio
    plan: free
    healthCheckPath: /health
    envVars:
      - key: Services__History
        value: https://qma-history-service.onrender.com/
      - key: Jwt__SecretKey
        value: btOUxwrOAwpVRLmc*#RfL8sdI#vYAZlgRuvO%qpRzxFHKq1V!
      - key: Jwt__Issuer
        value: QuantityMeasurementAPI
      - key: Jwt__Audience
        value: QuantityMeasurementClient

  - type: web
    name: qma-history-service
    runtime: docker
    dockerContext: .
    dockerfilePath: HistoryService/Dockerfile
    region: ohio
    plan: free
    healthCheckPath: /health
    envVars:
      - key: ConnectionStrings__DefaultConnection
        fromDatabase:
          name: qma-db
          property: connectionString
      - key: Jwt__SecretKey
        value: btOUxwrOAwpVRLmc*#RfL8sdI#vYAZlgRuvO%qpRzxFHKq1V!
      - key: Jwt__Issuer
        value: QuantityMeasurementAPI
      - key: Jwt__Audience
        value: QuantityMeasurementClient

  - type: web
    name: qma-admin-service
    runtime: docker
    dockerContext: .
    dockerfilePath: AdminService/Dockerfile
    region: ohio
    plan: free
    healthCheckPath: /health
    envVars:
      - key: Services__Auth
        value: https://qma-auth-service-p1hw.onrender.com/
      - key: Services__History
        value: https://qma-history-service.onrender.com/
      - key: Jwt__SecretKey
        value: btOUxwrOAwpVRLmc*#RfL8sdI#vYAZlgRuvO%qpRzxFHKq1V!
      - key: Jwt__Issuer
        value: QuantityMeasurementAPI
      - key: Jwt__Audience
        value: QuantityMeasurementClient

  - type: web
    name: qma-api-gateway
    runtime: docker
    dockerContext: .
    dockerfilePath: ApiGateway/Dockerfile
    region: ohio
    plan: free
    healthCheckPath: /health
    envVars:
      - key: Services__Auth
        value: https://qma-auth-service-p1hw.onrender.com/
      - key: Services__Quantity
        value: https://qma-quantity-service.onrender.com/
      - key: Services__History
        value: https://qma-history-service.onrender.com/
      - key: Services__Admin
        value: https://qma-admin-service.onrender.com/
      - key: Jwt__SecretKey
        value: btOUxwrOAwpVRLmc*#RfL8sdI#vYAZlgRuvO%qpRzxFHKq1V!
      - key: Jwt__Issuer
        value: QuantityMeasurementAPI
      - key: Jwt__Audience
        value: QuantityMeasurementClient

# ── DATABASE ──────────────────────────────────────────────────────────────────
databases:
  - name: qma-db
    databaseName: qmadb
    user: qmauser
    region: ohio
    plan: free
